import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { motion } from "framer-motion"
import { useState } from 'react'

export default function Home() {
  
  const [isActive, setIsActive] = useState(false);
  const [isVisible, setIsVisible] = useState(false);

  const WaterVariants = {
    animate: {
      x: -100, 
      y: -30,
    }
  };
  
  const FireVariants = {
    paused: {
      scale: 0.3,
      x: 0,
      y: 0,
    },
    moved: {
      backgroundColor: ["#FAC000", "#FF7500", "#FC6400", "#D73502"],
      scale: 1.5,
      y: 20,
      transition: {
        delay: 1,
        duration: 0.5,
        // ease: [0.17, 0.67, 0.83, 0.67],
        ease: "circOut",
        repeat: Infinity,
        repeatType: "reverse"
      }
    }
  };

  return (
    <motion.div className={styles.container}
      animate={{
        backgroundColor: isActive ? "#000" : "#fff",
        color: isActive ? "#fff" : "",
      }}
    >
      <Head>
        <title>Avatar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Long ago, the four nations lived together in<br />
          
          {/* Example 1: heading animation using hover */}
          <motion.a className={styles.harmony} whileHover={
              {fontSize: "120px"}
            }
          href="https://avatar.fandom.com/wiki/Official_Avatar_Aang_Fan_Club" target="_blank">harmony</motion.a>

        </h1>

        <div className={styles.grid}>
          
          {/* Example 2: Water animation using default variants */}
          <motion.a variants={WaterVariants} initial='initial' animate='animate'
            href="https://explore.org/livecams/sharks/shark-cam" className={`${styles.card} ${styles.water}`} target="_blank">
            <h2>Water</h2>
          </motion.a>
          
          {/* Example 3: Earth animation using transitions */}
          <motion.a animate={{
              scale: 1.5,
              x: -50
            }}
            transition={{
              duration: 3,
              delay: 0.3,
              repeat: 5,
              repeatType: "reverse",
            }}
            href="https://thisissand.com/" className={`${styles.card} ${styles.earth}`} target="_blank">
            <h2>Earth</h2>
          </motion.a>
          
          {/* Example 4: Fire animation rave style with easing */}
          <motion.a variants={FireVariants} initial="paused" animate="moved"
           href="https://freefireplaces.com/#" className={`${styles.card} ${styles.fire}`} target="_blank">
            <h2>Fire</h2>
          </motion.a>

          {/* Example 5: Air animation setting initial opacity */}
          <motion.a initial = {{y: -300, opacity: 0}}
            animate={{
              width: "200px",
              opacity: 1,
              x: 20,
              y: 0, 
            }}
            transition={{
              type: "spring",
              duration: 3,
              delay: 0.3,
              repeat: Infinity,
              repeatType: "mirror",
            }}
            href="https://bubblespop.netlify.app/" className={`${styles.card} ${styles.air}`}  target="_blank">
            <h2>Air</h2>
          </motion.a>
        </div>
        
        {/* Example 5: Attack animation on click */}
        <div className={styles.description}>
          Then, everything changed when the Fire Nation
          <motion.button onClick={() => setIsActive(!isActive)}> 
            attacked
          </motion.button>
        </div>
        <motion.div
          initial={{
            opacity: 0,
            height: 0,
            width: 0,
          }}
          animate={{
            scale: isActive ? 5 : 1,
            opacity: isActive ? 1 : 0,
            height: isActive ? 500 : 0,
            width: isActive ? 500 : 0,
          }}
          transition={{
            duration: 0.8,
            delay: 0.3,
            repeat: 1,
            repeatType: "reverse",
          }}
          >
          <Image className={styles.fireImage} src="/images/hehehe_fire.png" alt="flames" width={500} height={500} />
        </motion.div>

        <p className={styles.description}>
          Only the Avatar, master of all four elements, could stop them<br />but when the world needed him most<br />
          <b>he vanished</b>
        </p>

        {/* Example 6: Avatar disappear */}
        <motion.div onClick={() => setIsVisible(!isVisible)} 
            animate={{
              opacity: isVisible ? 0 : 1,
            }}
            transition={{
              type: "spring",
              duration: 2
            }}
          >
          <Image src="/images/aang.png" alt="last airbender" width={500} height={500} />
        </motion.div>

      </main>

      <footer className={styles.footer}>
        Powered by The Four Elements
      </footer>
    </motion.div>
  )
}
